services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DATASOURCE_NAME:-database}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD:-secret}
      - POSTGRES_USER=${DATASOURCE_USER:-postgres}
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.15-alpine
    ports:
      - 6379:6379
  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml