services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DATASOURCE_NAME:-database}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD:-secret}
      - POSTGRES_USER=${DATASOURCE_USER:-postgres}
    ports:
      - '5432:5432'
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
volumes:
  grafana_storage: