server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:
  - job_name: system
    static_configs:
      - targets:
        - localhost
        labels:
          job: scraper_api
          __path__: /logs/api/*log
      - targets:
        - localhost
        labels:
          job: varlogs
          __path__: /logs/syslogs/*log