global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "api"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets: ["api:8080"]